#!/usr/bin/env python3
"""Turn the splash logo slices into A8 LVGL image descriptors.

Each slice is an 8-bit grayscale PNG of white artwork on black; the gray level
becomes the alpha, so the part draws the same over the black splash.
"""

import re
import struct
import sys
import zlib
from pathlib import Path


def read_gray_png(path: Path) -> tuple[int, int, bytes]:
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError(f"{path}: not a PNG")
    pos, idat, width, height = 8, b"", 0, 0
    while pos < len(data):
        length, kind = struct.unpack(">I4s", data[pos:pos + 8])
        chunk = data[pos + 8:pos + 8 + length]
        if kind == b"IHDR":
            width, height, depth, ctype, _, _, interlace = struct.unpack(">IIBBBBB", chunk)
            if depth != 8 or ctype != 0 or interlace != 0:
                raise ValueError(f"{path}: expected 8-bit grayscale, not interlaced")
        elif kind == b"IDAT":
            idat += chunk
        pos += 12 + length

    raw = zlib.decompress(idat)
    out = bytearray()
    prev = bytearray(width)
    for y in range(height):
        start = y * (width + 1)
        kind = raw[start]
        line = bytearray(raw[start + 1:start + 1 + width])
        for x in range(width):
            a = line[x - 1] if x else 0
            b = prev[x]
            c = prev[x - 1] if x else 0
            if kind == 1:
                line[x] = (line[x] + a) & 255
            elif kind == 2:
                line[x] = (line[x] + b) & 255
            elif kind == 3:
                line[x] = (line[x] + ((a + b) >> 1)) & 255
            elif kind == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                line[x] = (line[x] + (a if pa <= pb and pa <= pc else b if pb <= pc else c)) & 255
        out += line
        prev = line
    return width, height, bytes(out)


def main() -> None:
    paths = [Path(argument) for argument in sys.argv[1:]]
    layout = next(path for path in paths if path.name == "layout.txt")
    pngs = {path.stem: path for path in paths if path.suffix == ".png"}

    text = layout.read_text()
    size = re.search(r"(\d+)x(\d+)", text)
    if size is None:
        raise ValueError("layout.txt must name the design size as WxH")
    lines = [line.split("#")[0].split() for line in text.splitlines()]
    parts = [(name, int(x), int(y)) for name, x, y in (line for line in lines if line)]

    print("// Generated by generate_splash_header.py. Do not edit.")
    print("#pragma once")
    print()
    print("struct gui2_splash_part {")
    print("  const char* name;")
    print("  int x;")
    print("  int y;")
    print("  lv_image_dsc_t image;")
    print("};")
    print()
    print(f"static constexpr int kGui2SplashWidth = {size.group(1)};")
    print(f"static constexpr int kGui2SplashHeight = {size.group(2)};")
    print()
    for name, _, _ in parts:
        width, height, pixels = read_gray_png(pngs["yarp_" + name])
        print(f"static const uint8_t kGui2Splash_{name}[] = {{")
        for offset in range(0, len(pixels), 24):
            print("  " + ",".join(str(value) for value in pixels[offset:offset + 24]) + ",")
        print("};")
        print()

    print("static const gui2_splash_part kGui2SplashParts[] = {")
    for name, x, y in parts:
        width, height, _ = read_gray_png(pngs["yarp_" + name])
        print(f'  {{ "{name}", {x}, {y},')
        print("    { .header = { .magic = LV_IMAGE_HEADER_MAGIC,")
        print("                  .cf = LV_COLOR_FORMAT_A8,")
        print("                  .flags = 0,")
        print(f"                  .w = {width}, .h = {height},")
        print(f"                  .stride = {width}, .reserved_2 = 0 }},")
        print(f"      .data_size = sizeof(kGui2Splash_{name}),")
        print(f"      .data = kGui2Splash_{name},")
        print("      .reserved = nullptr, .reserved_2 = nullptr } },")
    print("};")


if __name__ == "__main__":
    main()
